import { Region } from "./region";

export const ListRegions:Region[]=[
    {
        nom:'Analamanga',
        district:[
        {
            nom: 'Ambohidratrimo',
            code:1
        },
        { 
            nom: 'Andramasina',
            code:1
        },   
        {
            nom: 'Anjozorobe',
            code:1
        },
        {   
            nom: 'Ankazobe',
            code:1 
        },
        {   
            nom: 'Antananarivo Atsimondrano',
            code:1 
        },
        { 
            nom: 'Antananarivo Avaradrano',
            code:1 
        },
        { 
            nom: 'Antananarivo I',
            code:1 
        },
        { 
            nom: 'Antananarivo II',
            code:1 
        },
        { 
            nom: 'Antananarivo III',
            code:1 
        },
        { 
            nom: 'Antananarivo IV', 
            code:1
        },
        { 
            nom: 'Antananarivo V',
            code:1 
        },
        { 
            nom: 'Antananarivo VI',
            code:1 
        },
        { 
            nom: 'Manjakandriana',
            code:1
        }
        ]    
    },
    {
        nom:'Bongolava',
        district:[
            {
                nom:'Fenoarivobe',
                code:1
            },
            { 
                nom:'Tsiroanomandidy',
                code:1
            },
        ]
    },
    {
        nom:'Itasy',
        district:[
            {
                nom:'Arivonimamo',
                code:1
            },
            {
                nom:'Miarinarivo',
                code:1
            },
            {
                nom:'Soavinandriana',
                code:1
            },
        ]
    },    
    {
        nom:'Vakinakaratra',
        district:[
            {
                nom:'Ambatolampy',
                code:1
            },
            {
                nom:'Antanifotsy',
                code:1
            },
            {
                nom:'Antsirabe I',
                code:1
            },
            {
                nom:'Antsirabe II',
                code:1
            },
            {
                nom:'Betafo',
                code:1
            },
            {
                nom:'Faratsiho',
                code:1
            },
            {
                nom:'Mandoto',
                code:1
            },
        ]
    },
    {
        nom:'Diana',
        district:[
            {
                nom:'Ambanja',
                code:1
            },
            {
                nom:'Ambilobe',
                code:1
            },
            {
                nom:'Antsiranana I',
                code:1
            },
            {
                nom:'Antsiranana II',
                code:1
            },
            {
                nom:'Nosy Be',
                code:1
            },
        ]
    },
    {
        nom:'Sava',
        district:[
            {
                nom:'Andapa',
                code:1
            },
            {
                nom:'Antalaha',
                code:1
            },
            {
                nom:'Sambava',
                code:1
            },
            {
                nom:'Vohemar',
                code:1
            },
        ]
    },
    {
        nom:'Amoron\'i Mania',
        district:[
            {
                nom:'Ambatofinandrahana',
                code:1
            },
            {
                nom:'Ambositra',
                code:1
            },
            {
                nom:'Fandriana',
                code:1
            },
            {
                nom:'Manandriana',
                code:1
            },
        ]
    },
    {
        nom:'Antsimo Antsinanana',
        district:[
            {
                nom:'Befotaka',
                code:1
            },
            {
                nom:'Farafangana',
                code:1
            },
            {
                nom:'Midongy',
                code:1
            },
            {
                nom:'Vangaindrano',
                code:1
            },
            {
                nom:'Vondrozo',
                code:1
            },
        ]
    },
    {
        nom:'Fitovinany',
        district:[
            {
                nom:'Ikongo',
                code:1
            },
            {
                nom:'Manakara',
                code:1
            },
            {
                nom:'Vohipeno',
                code:1
            },
        ]
    },
    {
        nom:'Haute Matsiatra',
        district:[
            {
                nom:'Ambalavao',
                code:1
            },
            {
                nom:'Ambohimahasoa',
                code:1
            },
            {
                nom:'Fianarantsoa',
                code:1
            },
            {
                nom:'Ikalamavony',
                code:1
            },
            {
                nom:'Isandra',
                code:1
            },
            {
                nom:'Lalangina',
                code:1
            },
            {
                nom:'Vohibato',
                code:1
            }
        ]
    },
    {
        nom:'Ihorombe',
        district:[
            {
                nom:'Iakora',
                code:1
            },
            {
                nom:'Ihosy',
                code:1
            },
            {
                nom:'Ivohibe',
                code:1
            },
        ]
    },
    {
        nom:'Betsiboka',
        district:[
            {
                nom:'Kandreho',
                code:1
            },
            {
                nom:'Maevatanana',
                code:1
            },
            {
                nom:'Tsaratanana',
                code:1
            },
        ]
    },
    {
        nom:'Vatovavy',
        district:[
            {
                nom:'Ifanadiana',
                code:1
            },
            {
                nom:'Mananjary',
                code:1
            },
            {
                nom:'Nosy Varika',
                code:1
            },
        ]
    },
    {
        nom:'Boeny',
        district:[
            {
                nom:'Ambato-Boeny',
                code:1
            },
            {
                nom:'Mahajanga I',
                code:1
            },
            {
                nom:'Mahajanga II',
                code:1
            },
            {
                nom:'Marovoay',
                code:1
            },
            {
                nom:'Mitsinjo',
                code:1
            },
            {
                nom:'Soalala',
                code:1
            },
        ]
    },
    {
        nom:'Melaky',
        district:[
            {
                nom:'Ambatomainty',
                code:1
            },
            {
                nom:'Antsalova',
                code:1
            },
            {
                nom:'Besalampy',
                code:1
            },
            {
                nom:'Maintirano',
                code:1
            },
            {
                nom:'Morafenobe',
                code:1
            },
        ]
    },
    {
        nom:'Sofia',
        district:[
            {
                nom:'Analalava',
                code:1
            },
            {
                nom:'Antsohihy',
                code:1
            },
            {
                nom:'Bealanana',
                code:1
            },
            {
                nom:'Befandriana',
                code:1
            },
            {
                nom:'Mampikony',
                code:1
            },
            {
                nom:'Mandritsara',
                code:1
            },
            {
                nom:'Port-Bergé',
                code:1
            },
        ]
    },
    {
        nom:'Alaotra-Mangoro',
        district:[
            {
                nom:'Ambatondrazaka',
                code:1
            },
            {
                nom:'Amparafaravola',
                code:1
            },
            {
                nom:'Andilamena',
                code:1
            },
            {
                nom:'Anosibe an\'Ala',
                code:1
            },
            {
                nom:'Moramanga',
                code:1
            }
        ]
    },
    {
        nom:'Analanjirofo',
        district:[
            {
                nom:'Fenoarivo Atsinanana',
                code:1
            },
            {
                nom:'Mananara Nord',
                code:1
            },
            {
                nom:'Maroantsetra',
                code:1
            },
            {
                nom:'Maroantsetra',
                code:1
            },
            {
                nom:'Sainte-Marie',
                code:1
            },
            {
                nom:'Soanierana Ivongo',
                code:1
            },
            {
                nom:'Vavatenina',
                code:1
            }
        ]
    },
    {
        nom:'Atsinanana',
        district:[
            {
                nom:'Antanambao Manampontsy',
                code:1
            },
            {
                nom:'Brickaville',
                code:1
            },
            {
                nom:'Mahanoro',
                code:1
            },
            {
                nom:'Marolambo',
                code:1
            },
            {
                nom:'Toamasina I',
                code:1
            },
            {
                nom:'Toamasina II',
                code:1
            },
            {
                nom:'Vatomandry',
                code:1
            }
        ]
    },
    {
        nom:'Androy',
        district:[
            {
                nom:'Ambovombe',
                code:1
            },
            {
                nom:'Bekily',
                code:1
            },
            {
                nom:'Beloha',
                code:1
            },
            {
                nom:'Tsihombe',
                code:1
            }
        ]
    },
    {
        nom:'Anosy',
        district:[
            {
                nom:'Amboasary',
                code:1
            },
            {
                nom:'Betroka',
                code:1
            },
            {
                nom:'Tôlagnaro',
                code:1
            }
        ]
    },
    {
        nom:'Antsimo-Andrefana',
        district:[ 
            {
                nom:'Ampanihy',
                code:1
            },
            {
                nom:'Ankazoabo',
                code:1
            },
            {
                nom:'Benenitra',
                code:1
            },
            {
                nom:'Beroroha',
                code:1
            },
            {
                nom:'Betioky',
                code:1
            },
            {
                nom:'Morombe',
                code:1
            },
            {
                nom:'Sakaraha',
                code:1
            },
            {
                nom:'Toliara I',
                code:1
            },
            {
                nom:'Toliara II',
                code:1
            }
        ]
    },
    {
        nom:'Menabe',
        district:[
            {
                nom:'Belo sur Tsiribihina',
                code:1
            },
            {
                nom:'Mahabo',
                code:1
            },
            {
                nom:'Manja',
                code:1
            },
            {
                nom:'Miandrivazo',
                code:1
            },
            {
                nom:'Morondava',
                code:1
            },           
        ]
    }
]